language: java

python:
  - "3.6"

# for cmake >= 2.8.12
dist: trusty

addons:
  apt:
    packages:
      cmake
      libkrb5-dev
      lcov

install:
  - pip install coveralls nose coveralls-merge
  - gem install coveralls-lcov

after_success:
  - lcov -c -d target/CMakeFiles/kerberos-connector.dir -b target/CMakeFiles/kerberos-connector.dir --output-file target/lcov.info
  - coveralls-lcov -v -n target/lcov.info > target/coverage.c.json
  - coveralls-merge target/coverage.c.json target/coverage.java.json
