language: java

# for cmake >= 2.8.12
dist: trusty

sudo: true

addons:
  apt:
    packages:
      cmake
      libkrb5-dev
      lcov
      python3
      python3-pip

install:
  - sudo pip3 install coveralls nose coveralls-merge
  - gem install coveralls-lcov

after_success:
  - lcov -c -d target/jni-debug/CMakeFiles/kerberos-connector.dir -b target/jni-debug/CMakeFiles/kerberos-connector.dir --output-file target/lcov.info
  - coveralls-lcov -v -n target/lcov.info > target/coverage.c.json
  - coveralls-merge target/coverage.c.json target/coverage.java.json
