/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_zcu_KerberosConnector */

#ifndef _Included_cz_zcu_KerberosConnector
#define _Included_cz_zcu_KerberosConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_zcu_KerberosConnector
 * Method:    krb5_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cz_zcu_KerberosConnector_krb5_1init
  (JNIEnv *, jobject, jclass);

/*
 * Class:     cz_zcu_KerberosConnector
 * Method:    krb5_destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cz_zcu_KerberosConnector_krb5_1destroy
  (JNIEnv *, jobject);

/*
 * Class:     cz_zcu_KerberosConnector
 * Method:    krb5_renew
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cz_zcu_KerberosConnector_krb5_1renew
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
